### ISSUE TITLE
Qt5 compatibility and moc file.

### ISSUE THREAD

**Issue by AlfredoRamos** [vkohaupt/vokoscreen#100]
As title says, it needs some fixes, it uses some obsolete functions in Qt5 (i.e. (```QDesktopServices::storageLocation()``` -> (Qt5) ```QStandardPaths::writableLocation()```).

I've solved that, but there's something that i can't figure out.

```
moc_screencast.o: In function `screencast::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
Makefile:350: recipe for target 'vokoscreen' failed
/home/abaddon/Public/vokoscreen/build-Desktop-Debug/moc_screencast.cpp:402: undefined reference to `screencast::selectRecorder()'
collect2: error: ld returned 1 exit status
make: *** [vokoscreen] Error 1
22:21:40: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project vokoscreen (kit: Desktop)
When executing step "Make"
22:21:40: Elapsed time: 00:05.
```

I haven't faced problems with moc files, so i don't know what to do, i've made a research with no luck.

PS: I have Qt 5.4.1 x86_64.

**Comment by rumbler** [comment]
this error is because there is a prototype of selectRecorder () function in screencast.h but was declared screencast.cpp only if the version of QT4, in your case this using QT5 it takes probably make a statement to QT5.
One possible solution "worked for me" would add just after the declaration for QT4 starting on line 1448 a statement to the QT5.
#ifdef QT5
void screencast :: selectRecorder ()
{QString recorder = QFileDialog :: getOpenFileName (this, tr ("Select recorder"), QStandardPaths :: writableLocation (QStandardPaths :: HomeLocation)); if (recorder> "") RecorderLineEdit-> setText (recorder);
}
#endif

**Comment by AlfredoRamos** [comment]
Thanks @rumbler i didn't check that file (big mistake).

I've done this:

```cpp
void screencast::selectRecorder()
{
	QString recorder;

#ifdef QT4
	recorder = QFileDialog::getOpenFileName(
		this,
		tr( "Select recorder" ),
		QDesktopServices::storageLocation( QDesktopServices::HomeLocation )
	);
#endif

#ifdef QT5
	recorder = QFileDialog::getOpenFileName(
		this,
		tr("Select recorder"),
		QStandardPaths::writableLocation(QStandardPaths::HomeLocation)
	);
#endif

	if ( !recorder.isEmpty() )
		RecorderLineEdit->setText( recorder );
}
```

Now i can make a patch for the AUR git package.
