### ISSUE TITLE
Send to YouTube

### ISSUE THREAD

**Issue by orschiro** [vkohaupt/vokoscreen#129]
Dear all, 

I would like to hear your opinion for another option for the "Send" button to not only send a video via email but to directly upload it to YouTube. 

What do you think about such a feature?

Thankfully,

~Robert

**Comment by tuxmuck** [comment]
Here we did not know how that is programmatically to implement.
This is a bit difficult.
For this we need another programmer who could implement this -

**Comment by orschiro** [comment]
Hi @tuxmuck,

Does this source help?

https://developers.google.com/youtube/v3/guides/uploading_a_video

~Robert

**Comment by tuxmuck** [comment]
I know this code, but it is written in Python.
We program in C ++

**Comment by vkohaupt** [comment]
Hi Robert,

i can not work on so big program as a youtub uploader and I can work on 
vokoscreen only if time is to.

**Comment by orschiro** [comment]
Dear @tuxmuck and @vkohaupt,

I understand. 

Thank you for your responses!

~Robert

**Comment by J5lx** [comment]
In case there is any other person interested in working on this, the documentation for the actual API endpoint can be found at <https://developers.google.com/youtube/v3/docs/videos/insert>. I can’t help with the implementation myself since my own knowledge is limited to some basic C, and I understand that the lead developer is short on time, but maybe there’s somebody else who can use this as a starting point.

**Comment by tuxmuck** [comment]
> but maybe there’s somebody else who can use this

Hello world ! - :-)

**Comment by BiLachner** [comment]
I would like it, too ... but I'm not able to program it ... sorry.

**Comment by vkohaupt** [comment]
I read paragraph 21
https://developers.google.com/youtube/terms/api-services-terms-of-service-emea

In this case i see no way programming a Youtube-uplader.
