### ISSUE TITLE
Vokoscreen cannot recognize Xplayer

### ISSUE THREAD

**Issue by pkail** [vkohaupt/vokoscreen#230]
I removed VLC because it installed a version of ffmpeg which stopped Vokoscreen from working.  I would like to use Xplayer, which is the default in Mint, but this doesn't appear on the drop-down list.  I added videoplayer=xplayer in vokoscreen.config, but this didn't do the trick, either.

**Comment by Martii** [comment]
> videoplayer=xplayer in vokoscreen.config, but this didn't do the trick, either.

See https://github.com/vkohaupt/vokoscreen/issues/194#issuecomment-343758219 and forward.

> I would like to use Xplayer, which is the default in Mint

See https://github.com/vkohaupt/vokoscreen/blob/3723046ca1e3f24241ab40392ec12c379d9e34af/screencast.cpp#L1777-L1793 ... Perhaps you could compile it with your player added in there. I tried to find `xplayer` in my distro's package manager and no luck *(not running Mint)*. Ensure that `xplayer` isn't a symbolic link to something else too.

Looking at the code I don't think it pulls the MIME types in this version for available players but uses a predefined list of "popular" players. "Standard system player" might do the trick if you set it up in your Applications *(MIME)* setup but unsure since I don't really have a fully working version myself to test out due to distro changes *(hence why they are on a "next gen" now... see below)*

> in vokoscreen.config

Perhaps you meant `vokoscreen.conf` :smile_cat: 

Please be aware that they are working on https://github.com/vkohaupt/vokoscreenNG now.
